---
title: "Cell type annotation - tissues"
params:
  seed: 42
  input_file: "/mnt/data/NGS/Projects/MCL-scrnaseq/MCL-PhanthomMenace/CellTypeAnnotation_final/SingleCellExperiment_PBMC_annotated.rds"
  output_file: "/mnt/data/NGS/Projects/MCL-scrnaseq/MCL-PhanthomMenace/CellTypeAnnotation_final/SingleCellExperiment_annotated.rds"
  sc_functions: "/mnt/data/NGS/Projects/MCL-scrnaseq/MCL-PhanthomMenace/scrnaseq-analysis-nxf/bin/sc_functions.R"
output: html_notebook
---

```{r setup}
seed <- params$seed
set.seed(seed)

# Load the libraries
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(Seurat)
  library(scater)
  library(scran)
  library(tricycle)
  library(SingleR)
  library(celldex)
  library(tidyverse)
  library(patchwork)
  library(ggridges)
})

path_sce_input <- params$input_file
path_sce_output <- params$output_file

sc_functions <- params$sc_functions
source(sc_functions)
```

# Total cell dataset

```{r load_sce}
sce_cells <- readRDS(path_sce_input)
sce_cells
```

# Manual annotations by TZ

```{r}
TZ_annot <- read_csv(
  "/mnt/data/NGS/Projects/MCL-scrnaseq/data-before_revision/scRNAseq/analysis/scripts/TZ_scripts/final_annotation.csv"
) %>%
  dplyr::select(-1) %>%
  mutate(
    cell_type_and_state = ifelse(
    is.na(cell_state_2),
    cell_state_1,
    paste(cell_state_1, cell_state_2, sep = "_")
  ),
  cell_type_and_state = ifelse(
    is.na(cell_type_and_state),
    cell_type,
    paste(cell_type, cell_type_and_state, sep = "_")
  )
  )
TZ_annot
```

```{r}
TZ_annot %>% 
  group_by(cell_type_and_state) %>% 
  reframe(cells = n())
```

```{r}
cell_annotations <- colData(sce_cells) %>% 
  as.data.frame() %>% 
  mutate(
    Sample_full = paste(Patient, Timepoint, Compartment, paste0("rep", Replicate), sep = "_"),
    barcode_sample = paste(Barcode, Sample_full, sep = "-")
  ) %>% 
  dplyr::select(Sample, cell_type_manual, barcode_sample) %>% 
  left_join(
    TZ_annot, by = join_by("barcode_sample" == "sample_barcode")
  ) %>% 
  mutate(
    cell_type_and_state = case_when(
      is.na(cell_type_and_state) ~ "Unassigned",
      TRUE ~ cell_type_and_state
    )
  )
cell_annotations
```

```{r}
sce_cells$cell_type <- cell_annotations$cell_type
sce_cells$cell_type_and_state <- cell_annotations$cell_type_and_state
```

# Tissue cells subset

```{r}
sce_tissues <- sce_cells[, sce_cells$Compartment != "PBMC"]
sce_tissues
```

```{r}
sce_tissues <- process_sce(
  sce_tissues,
  HVF_method = "seurat_vst",
  FindClusters_res = c(0.1, 0.5)
)
```

```{r fig.width=8, fig.height=6}
plotUMAP(sce_tissues, color_by = "Timepoint", other_fields = "Patient") +
  facet_wrap( ~ Patient) +
  theme_bw()
```

```{r fig.width=7, fig.height=5}
plotUMAP(sce_tissues, color_by = "cell_type_manual") +
  theme_void(base_size = 12)
```

```{r fig.width=10, fig.height=6}
plotUMAP(
  sce_tissues,
  color_by = "cell_type_manual",
  other_fields = c("Compartment", "Timepoint")
) +
  theme_bw(base_size = 12) +
  facet_wrap(Compartment ~ Timepoint)
```

```{r fig.width=9, fig.height=5}
plotUMAP(sce_tissues, color_by = "cell_type_and_state") +
  theme_void(base_size = 12)
```

```{r, fig.width=9, fig.height=8}
plotContingency(sce_tissues, columns = "cell_type_manual", rows = "cell_type_and_state")
```

```{r, fig.width=15, fig.height=5}
plotExpression(sce_tissues,
               x = "cell_type_and_state",
               features = "CCND1",
               color_by = "cell_type_manual"
) +
  theme(
    axis.text.x = element_text(
      size = 12,
      angle = 70,
      hjust = 1
    )
  )
```

```{r fig.width=6, fig.height=5}
plotUMAP(sce_tissues, color_by = "CCND1")
```

```{r, fig.width=9, fig.height=8}
# re-assign obviously malignant cells in TZ's annots
sce_tissues$cell_type_and_state <- colData(sce_tissues) %>%
  as.data.frame() %>%
  dplyr::select(cell_type_manual, cell_type_and_state) %>%
  mutate(cell_type_and_state = case_when(
    (
      cell_type_and_state == "Unassigned" |
        cell_type_and_state == "malignant" | cell_type_and_state == "low_quality_cell"
    ) &
      cell_type_manual == "MCL cells" ~ cell_type_manual,
    TRUE ~ cell_type_and_state
  )) %>%
  pull(cell_type_and_state)

plotContingency(sce_tissues, columns = "cell_type_manual", rows = "cell_type_and_state")
```

```{r}
sce_tissues_norm <- sce_tissues[, sce_tissues$cell_type_manual != "MCL cells"]
sce_tissues_norm
```

```{r}
sce_tissues_norm <- process_sce(
  sce_tissues_norm,
  HVF_method = "seurat_vst",
  n_HVFs = 1000,
  vars_to_regress = "tricyclePhase",
  FindClusters_res = c(0.1, 0.2, 0.5)
)
```

```{r fig.width=5, fig.height=4.5}
cluster_res <- "clusters_res_0.1"

plotUMAP(sce_tissues_norm,
         color_by = cluster_res,
         text_by = cluster_res,
         text_size = 6
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "Cluster"))
```

```{r fig.width=5, fig.height=4.5}
plotUMAP(sce_tissues_norm,
         color_by = "tricyclePhase",
         text_size = 6
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "CC phase"))
```

```{r fig.width=6, fig.height=4.5}
plotUMAP(sce_tissues_norm,
         color_by = "cell_type_manual",
         text_size = 6
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "CC phase"))
```

```{r}
markers <- effectSizeMarkers(sce_tissues_norm,
                             group = cluster_res,
                             AUC_up_thresh = 0.7,
                             AUC_down_thresh = 0.3,
                             logFC.cohen_thresh = 0.5)
markers
```

```{r}
markers_to_text(markers, max_length = 30)
```

## T and NK cells

## PBMC T cells

```{r}
sce_TNK <- sce_tissues_norm[, sce_tissues_norm$cell_type_manual == "NK/T cells"]
sce_TNK
```

```{r}
sce_TNK <- process_sce(
  sce_TNK,
  HVF_method = "scran_mgv",
  FindClusters_res = c(0.1, 0.5, 0.8)
)
```

```{r fig.width=8, fig.height=4}
plotUMAP(sce_TNK, color_by = "CD3E") +
  theme_void(base_size = 12) +
  plotUMAP(sce_TNK, color_by = "CD3D") +
  theme_void(base_size = 12)
```

```{r fig.width=9, fig.height=4.5}
plotUMAP(sce_TNK, color_by = "cell_type_and_state") +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "Cluster"))
```

```{r fig.width=5, fig.height=4.5}
cluster_res <- "clusters_res_0.5"

plotUMAP(sce_TNK,
         color_by = cluster_res,
         text_by = cluster_res,
         text_size = 6
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "Cluster"))
```

```{r fig.width=10, fig.height=8}
plotUMAP(sce_TNK, color_by = cluster_res,
         other_fields = c("Sample", "Compartment")) +
  facet_wrap(Compartment ~ Sample) +
  theme_bw()
```

```{r fig.width=8, fig.height=6}
plotContingency(sce_TNK, columns = cluster_res, rows = "cell_type_and_state")
```

### NK cells

```{r, fig.width=5, fig.height=4, message=FALSE}
marker_genes <- list(
  "T cells" = c("CD3E", "CD3D"),
  "NK cells" = c("NCAM1", "KLRF1", "FGFBP2", "XCL1", "KLRC3", "KLRD1", "PRF1")
)

plotDots_twotailed(
  sce_TNK,
  group = cluster_res,
  high = c("NCAM1", "KLRF1", "FGFBP2", "XCL1", "KLRC3", "KLRD1", "PRF1"),
  low = c("CD3E", "CD3D")
)
```

```{r}
sce_NK <- sce_TNK[, sce_TNK[[cluster_res]] %in% c(6)]

sce_NK %>% 
  colData() %>% as.data.frame() %>% 
  group_by(cell_type_and_state) %>% 
  reframe(cells = n())
```

```{r}
sce_NK <- process_sce(
  sce_NK,
  HVF_method = "scran_mgv",
  HVF_fdr_threshold = 0.25,
  UMAP_min_dist = 0.5,
  FindClusters_res = c(0.1, 0.5, 0.8, 1)
)
```

```{r fig.width=6, fig.height=5}
cluster_res <- "clusters_res_1"

plotUMAP(sce_NK,
         color_by = cluster_res,
         text_by = cluster_res
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "Cluster"))
```

```{r fig.width=6, fig.height=5}
plotUMAP(sce_NK,
         color_by = "cell_type_and_state"
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = ""))
```

```{r fig.width=5, fig.height=3}
plotContingency(sce_NK, columns = cluster_res, rows = "cell_type_and_state")
```

```{r}
markers <- effectSizeMarkers(sce_NK,
                             group = cluster_res,
                             AUC_up_thresh = 0.6,
                             logFC.cohen_thresh = 0.25
                             )
markers_to_text(markers)
```

```{r fig.width=4.5, fig.height=8}
max_length = 40
plots <- list()
for (i in unique(markers$cluster)) {
  markers_high <- markers %>% 
    filter(!str_detect(gene, "^RP[LS]")) %>%
    filter(cluster == i) %>%
    slice_head(n = max_length) %>%
    filter(change == "up") %>% pull(gene)
  markers_low <- markers %>% 
    filter(!str_detect(gene, "^RP[LS]")) %>%
    filter(cluster == i) %>%
    slice_head(n = max_length) %>%
    filter(change == "down") %>% pull(gene)
  
  plots[[i]] <- plotDots_twotailed(
    sce_NK,
    group = cluster_res,
    title = paste0("C", i),
    high = markers_high,
    low = markers_low,
  )
}
plots
```

```{r fig.width=2.5, fig.height=5.5}
plotDots_twotailed(
  sce_NK,
  group = cluster_res,
  title = "NK cells - naive",
  high = c("NCAM1", "SELL", "TCF7", "IL7R", "TPT1", "CD44", "TNFRSF18"),
  low = c("FCGR3A", "PRF1", "GZMA", "GZMB"),
  zlim = c(-1, 1.5)
) +
  theme(legend.position = "none")
```

```{r fig.width=2.5, fig.height=5}
plotDots_twotailed(
  sce_NK,
  group = cluster_res,
  title = "NK cells - mature",
  high = c("FCGR3A", "FGFBP2", "PRF1", "GZMA", "GZMB", "CX3CR1"),
  low = c("GZMK", "KLRC2", "EEF1A1"),
  zlim = c(-1, 1.5)
) +
  theme(legend.position = "none")
```

```{r, fig.width=2.5, fig.height=5}
plotDots_twotailed(
    sce_NK,
    group = cluster_res,
    title = "NK cells - adaptive",
    high = c("KLRC2", "CCL5", "CMC1", "PIK3R1"),
    low = c("FGFBP2", "GNLY"),
    zlim = c(-1, 1.5)
) +
  theme(legend.position = "none")
```

```{r fig.width=3.5, fig.height=5}
plotDots_twotailed(
  sce_NK,
  group = cluster_res,
  title = "NK cells - mature + adaptive",
  high = c("FGFBP2", "GZMB", "FCGR3A", "PRF1", "KLRC2", "GNLY", "GZMA"),
  zlim = c(-1, 1.5)
)
```

```{r}
sce_NK$clusters <- sce_NK[[cluster_res]]

cells_df <- colData(sce_NK) %>% 
  as.data.frame() %>% 
  remove_rownames() %>% 
  dplyr::select(clusters) %>% 
  distinct() %>% 
  arrange(clusters) %>% 
  mutate(
    cell_type_manual = case_when(
      clusters %in% c(3) ~ "NK cells - naive",
      clusters %in% c(1) ~ "NK cells - adaptive",
      clusters %in% c(2, 4) ~ "NK cells - mature",
      clusters %in% c(5) ~ "NK cells - tissue-resident"
    )
  )

cluster_to_cells <- setNames(cells_df$cell_type, cells_df$clusters)
colData(sce_NK)$cell_type_manual <- cluster_to_cells[as.character(colData(sce_NK)$clusters)]

data.frame(
  cell_type_manual = sce_NK$cell_type_manual
) %>% 
  group_by(cell_type_manual) %>% 
  reframe(N = n())
```

```{r fig.width=6, fig.height=5}
plotUMAP(sce_NK,
         color_by = "cell_type_manual"
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = ""))
```

```{r}
plotContingency(sce_NK, columns = "cell_type_manual", rows = "cell_type_and_state")
```

```{r}
# Add subset annotations to the main set
subset_cell_types <- sce_NK %>%
  colData() %>% as.data.frame() %>%
  dplyr::select(Sample_Barcode, "refined_cell_type" = cell_type_manual)

mainset_cell_types <- colData(sce_TNK) %>% as.data.frame() %>%
  dplyr::select(Sample_Barcode, cell_type_manual)

sce_TNK$cell_type_manual <- left_join(mainset_cell_types, subset_cell_types, by = join_by(Sample_Barcode)) %>%
  mutate(cell_type_manual = case_when(
    is.na(refined_cell_type) ~ cell_type_manual,
    TRUE ~ refined_cell_type
  )) %>%
  pull(cell_type_manual)

data.frame(cell_type_manual = sce_TNK$cell_type_manual) %>%
  group_by(cell_type_manual) %>%
  reframe(N = n())
```

```{r fig.width=6, fig.height=5}
plotUMAP(sce_TNK,
         color_by = "cell_type_manual"
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = ""))
```

### T cells

```{r}
sce_T <- sce_TNK[, sce_TNK$cell_type_manual == "NK/T cells"]
sce_T
```

```{r}
colData(sce_T) %>% 
  as.data.frame() %>% 
  group_by(Patient, Timepoint, Compartment) %>% 
  reframe(cells = n())
```

```{r}
sce_T <- process_sce(
  sce_T,
  HVF_method = "seurat_vst",
  n_HVFs = 2000,
  FindClusters_res = c(0.1, 0.5, 1, 1.1),
)
```

```{r fig.width=5, fig.height=4.5}
cluster_res <- "clusters_res_0.1"

plotUMAP(sce_T,
         color_by = cluster_res,
         text_by = cluster_res,
         text_size = 6
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "Cluster"))
```

```{r fig.width=15, fig.height=4.5}
plotUMAP(sce_T, color_by = "CD8A") +
  theme_void(base_size = 12) +
  plotUMAP(sce_T, color_by = "CD8B") +
  theme_void(base_size = 12) +
  plotUMAP(sce_T, color_by = "CD4") +
  theme_void(base_size = 12)
```

```{r, fig.width=5, fig.height=4, message=FALSE}
marker_genes <- list(
  "T cells" = c("CD3E", "CD3D"),
  "NK cells" = c("NCAM1", "KLRF1", "FGFBP2", "XCL1", "KLRC3", "KLRD1", "PRF1")
)

plotDots_twotailed(
  sce_T,
  group = cluster_res,
  high = c("NCAM1", "KLRF1", "FGFBP2", "XCL1", "KLRC3", "KLRD1", "PRF1"),
  low = c("CD3E", "CD3D")
)
```

```{r}
markers <- effectSizeMarkers(sce_T,
                             group = cluster_res,
                             AUC_up_thresh = 0.6,
                             logFC.cohen_thresh = 0.25
                             )
markers_to_text(markers, max_length = 60)
```

```{r, fig.width=4, fig.height=3.5}
plotDots_twotailed(
    sce_T,
    group = cluster_res,
    title = "CD8+/CD4+ T cells",
    high = c("CD8A", "CD8B", "GZMB", "RUNX3", "EOMES", "CD247"),
    low = c("CD4", "FOXP3", "RORC", "IL7R", "TCF7", "LDHB", "MAL"),
    zlim = c(-2.5, 2.5)
  )
```

```{r fig.width=10, fig.height=10}
plotUMAP(sce_T,
         color_by = cluster_res,
         other_fields = c("Sample", "Compartment")
         ) +
  theme_bw(base_size = 14) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "Cluster")) +
  facet_wrap(Compartment ~ Sample) +
  labs(x = NULL, y = NULL)
```

```{r fig.width=5, fig.height=4.5}
plotUMAP(sce_T,
         color_by = cluster_res,
         text_by = cluster_res,
         text_size = 6
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "Cluster"))
```

```{r, fig.width=4, fig.height=3.5}
plotDots_twotailed(
    sce_T,
    group = cluster_res,
    title = "CD8+/CD4+ T cells",
    high = c("CD8A", "CD8B", "GZMB", "RUNX3", "EOMES", "CD247"),
    low = c("CD4", "FOXP3", "RORC", "IL7R", "TCF7", "LDHB", "MAL"),
    zlim = c(-2.5, 2.5)
  )
```

```{r fig.width=5, fig.height=4.5}
cd8a_expr <- counts(sce_T)["CD8A", ] > 0
cd8b_expr <- counts(sce_T)["CD8B", ] > 0
cd4_expr <- counts(sce_T)["CD4", ] > 0

sce_T[["cd8_expr"]] <- colData(sce_T) %>% 
  as.data.frame() %>% 
  mutate(
    state_cd8a = cd8a_expr,
    state_cd8b = cd8b_expr,
    state_cd4 = cd4_expr,
    Tcell_state = case_when(
      (state_cd8a | state_cd8b) & !state_cd4 ~ "CD8+",
      !(state_cd8a | state_cd8b) & state_cd4 ~ "CD4+",
      (state_cd8a | state_cd8b) & state_cd4 ~ "CD8+; CD4+",
      !(state_cd8a | state_cd8b) & !state_cd4 ~ "none",
    )
  ) %>% 
  pull(Tcell_state)

plotUMAP(sce_T,
         color_by = "cd8_expr",
         text_size = 6
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = ""))
```

```{r}
colData(sce_T) %>% 
  as.data.frame() %>% 
  group_by(cd8_expr) %>% 
  reframe(cells = n())
```

```{r}
sce_T$clusters <- sce_T[[cluster_res]]

sce_T$cell_type_manual <- colData(sce_T) %>% 
  as.data.frame() %>% 
  remove_rownames() %>% 
  dplyr::select(clusters, cd8_expr) %>% 
  mutate(
    cell_type_manual = case_when(
      clusters %in% c(2, 3) | cd8_expr %in% c("CD8+") ~ "T cells - CD8+",
      TRUE ~ "T cells - CD4+"
    )
  ) %>% 
  pull(cell_type_manual)

data.frame(
  cell_type_manual = sce_T$cell_type_manual
) %>% 
  group_by(cell_type_manual) %>% 
  reframe(N = n())
```

```{r fig.width=5, fig.height=4.5}
plotUMAP(sce_T,
         color_by = "cell_type_manual",
         text_size = 6
         ) +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = "T cells"))
```

```{r}
# Add subset annotations to the main set
subset_cell_types <- sce_T %>%
  colData() %>% as.data.frame() %>%
  dplyr::select(Sample_Barcode, "refined_cell_type" = cell_type_manual)

mainset_cell_types <- colData(sce_TNK) %>% as.data.frame() %>%
  dplyr::select(Sample_Barcode, cell_type_manual)

sce_TNK$cell_type_manual <- left_join(mainset_cell_types, subset_cell_types, by = join_by(Sample_Barcode)) %>%
  mutate(cell_type_manual = case_when(
    is.na(refined_cell_type) ~ cell_type_manual,
    TRUE ~ refined_cell_type
  )) %>%
  pull(cell_type_manual)

data.frame(cell_type_manual = sce_TNK$cell_type_manual) %>%
  group_by(cell_type_manual) %>%
  reframe(N = n())
```

```{r fig.width=6.25, fig.height=4.5}
plotUMAP(sce_TNK, color_by = "cell_type_manual") +
  theme_void(base_size = 12) +
  guides(color = guide_legend(override.aes = list(size = 3), title = ""))
```



