services:
  rstudio:
    image: rstudio-server-scrnaseq:1.0
    ports:
      - "8080:8787"
    environment:
      - PASSWORD=single_cell
      - ROOT=TRUE
      - GROUPID=1001
      - USERID=1004
    volumes:
      - type: "bind"
        source: "/home/dmitryk/Projects/MCL-PhanthomMenace"
        target: "/home/rstudio/scrnaseq"
    restart: always
