---
title: "`r params$sample_id` - cell QC"
params:
  sample_id: "P069_REL_GUT"
  path_sce_input: "../results/QC/P069_REL_GUT/3_doublets/P069_REL_GUT_singlets.sce"
  path_perCellCont: "../results/QC/P069_REL_GUT/2_ambientRNA/P069_REL_GUT_perCellCont.rds"
  path_sce_output: "test_sce.rds"
  path_sce_output_cleaned: "test_sce_cleaned.rds"
  nUMI_thresh: 1000
  nGenes_thresh: 600
  mito_thresh: 20
  contam_thresh: 0.75
  cluster_discard_thresh: 0.33
  process_fun: "../bin/sc_functions.R"
  seed: 42
---

```{r setup}
sample_id <- params$sample_id
path_sce_input <- params$path_sce_input
path_perCellCont <- params$path_perCellCont
path_sce_output <- params$path_sce_output
path_sce_output_cleaned <- params$path_sce_output_cleaned

# thresholds
nUMI_thresh <- as.numeric(params$nUMI_thresh)
nGenes_thresh <- as.numeric(params$nGenes_thresh)
mito_thresh <- as.numeric(params$mito_thresh)
contam_threshold <- as.numeric(params$contam_thresh)
cluster_discard_thresh <- as.numeric(params$cluster_discard_thresh)

process_fun <- params$process_fun
source(process_fun)

seed <- params$seed
set.seed(seed)

# Load the libraries
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(Seurat)
  library(scater)
  library(scran)
  library(stringr)
  library(dplyr)
  library(patchwork)
})
```

# Read the sce

```{r load_sce}
sce <- readRDS(path_sce_input)

# Remove doublets detected in the previous step
sce <- sce[, sce$scDblFinder.class == "singlet"]

# Add QC metrics
QC.genes <- list(
    Mito = stringr::str_which(rowData(sce)[["Symbol"]], "^MT-"),
    Ribo = stringr::str_which(rowData(sce)[["Symbol"]], "^RPL")
    )

sce <- addPerCellQCMetrics(sce, subsets = QC.genes)

sce$libComplexity <- log10(sce$detected) / log10(sce$sum)
sce$Mito_Ribo_Ratio <- sce$subsets_Mito_percent / (sce$subsets_Mito_percent + sce$subsets_Ribo_percent)

sce
```

# QC metrics

```{r add_QC_metrics, fig.width=11.2, fig.height=7}
sce$damaged <- sce$sum < nUMI_thresh |
  sce$detected < nGenes_thresh |
  sce$subsets_Mito_percent > mito_thresh

basic_QC_plots(sce, "damaged", nUMI_thresh, nGenes_thresh, mito_thresh)
```


```{r, fig.width=11.2, fig.height=7}
advanced_QC_plots(sce, "damaged", nUMI_thresh, nGenes_thresh, mito_thresh)
```

```{r}
colData(sce) %>% 
  as.data.frame() %>% 
  mutate(
    threshold_QC = case_when(
      damaged ~ "Remove",
      !damaged ~ "Pass"
    )
  ) %>% 
  group_by(threshold_QC) %>% 
  reframe(cells = n())
```

# Ambient RNA contamination metrics

```{r assingn contamination profile, fig.width=11.2, fig.height=6}
perCellCont <- readRDS(path_perCellCont)

sce$contamination <- left_join(
  as.data.frame(colData(sce)),
  perCellCont,
  by = join_by("Barcode" == "cell")
) %>% 
  pull(cont)

advanced_QC_plots(sce, "contamination", nUMI_thresh, nGenes_thresh, mito_thresh)
```

```{r, fig.width=7, fig.height=6}
sce$contaminated <- as.data.frame(colData(sce)) %>% 
  mutate(
    contaminated = case_when(
      contamination > contam_threshold ~ TRUE,
      TRUE ~ FALSE)
  ) %>% 
  pull(contaminated)

contam_QC_plots(sce, "contaminated", contam_threshold, nUMI_thresh, nGenes_thresh, mito_thresh)
```

```{r fig.width=11.2, fig.height=4}
basic_QC_plots(sce, "contaminated", nUMI_thresh, nGenes_thresh, mito_thresh)
```


```{r, fig.width=11.2, fig.height=6}
advanced_QC_plots(sce, "contaminated", nUMI_thresh, nGenes_thresh, mito_thresh)
```

```{r}
colData(sce) %>% 
  as.data.frame() %>% 
  mutate(
    contamination_QC = case_when(
      contaminated ~ "Remove",
      !contaminated ~ "Pass"
    )
  ) %>% 
  group_by(contamination_QC) %>% 
  reframe(cells = n())
```

# Join discard and contamination

```{r}
sce$discard <- as.data.frame(colData(sce)) %>% 
  mutate(
    discard = case_when(
      contaminated | damaged ~ TRUE,
      TRUE ~ FALSE
    )
  ) %>% 
  pull(discard)

colData(sce) %>% 
  as.data.frame() %>% 
  mutate(
    discard_QC = case_when(
      discard ~ "Remove",
      !discard ~ "Pass"
    )
  ) %>% 
  group_by(discard_QC) %>% 
  reframe(cells = n())
```

```{r fig.width=7, fig.height=6}
contam_QC_plots(sce, "discard", contam_threshold, nUMI_thresh, nGenes_thresh, mito_thresh)
```

# Clustering

```{r}
sce <- process_sce(
  sce,
  HVF_method = "seurat_vst",
  n_HVFs = 2000,
  chosen_pcs = 20,
  FindClusters_res = 1,
  seed = seed
)
sce$QC_clusters <- sce$clusters_res_1
sce$clusters_res_1 <- NULL
```

```{r, fig.width=15, fig.height=4.5}
plotUMAP(sce,
         color_by = "QC_clusters",
         text_by = "QC_clusters") +
  plotUMAP(sce,
         color_by = "damaged") +
  plotUMAP(sce,
         color_by = "contaminated")
```

```{r, fig.width=15, fig.height=4.5}
plotUMAP(sce,
         color_by = "sum") +
  plotUMAP(sce,
         color_by = "detected") +
  plotUMAP(sce,
         color_by = "subsets_Mito_percent")
```

```{r, fig.width=15, fig.height=4.5}
plotUMAP(sce, color_by = "CD3E") +
  plotUMAP(sce, color_by = "IGKC") +
  plotUMAP(sce, color_by = "contamination")
```

# Discard problematic cells

```{r discard_rates}
cluster_discard_stats <- table(colData(sce)[["QC_clusters"]], colData(sce)[["discard"]])

cluster_discard_proportions <- prop.table(cluster_discard_stats, margin = 1)[, "TRUE"]

discard_rates <- data.frame(
  Cluster = names(cluster_discard_proportions),
  Cells = cluster_discard_stats[, "FALSE"],
  Discard = cluster_discard_stats[, "TRUE"],
  Discard_Rate = round(cluster_discard_proportions, 3)
)

discard_rates <- discard_rates[order(discard_rates$Discard_Rate, decreasing = TRUE), ]
discard_rates
```

```{r discard_rates_plot}
ggplot(discard_rates, aes(x = reorder(Cluster, -Discard_Rate), y = Discard_Rate)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  geom_hline(yintercept = cluster_discard_thresh, linetype = "dashed", color = "firebrick") +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent, limits = c(0, 1)) +
  labs(x = "Cluster", y = "Discard Rate", title = "Proportion of cells to discard by cluster")
```

```{r detect_problematic_clusters}
problematic_clusters <- names(cluster_discard_proportions[cluster_discard_proportions > cluster_discard_thresh])

if (length(problematic_clusters) > 0) {
  cat(
    "Removing the following clusters with >",
    cluster_discard_thresh * 100,
    "% discard rate:",
    paste(problematic_clusters, collapse = ", "),
    "\n"
  )
  
  # Mark cells in problematic clusters for removal
  problematic_cells <- colData(sce)$QC_clusters %in% problematic_clusters
  colData(sce)$cluster_discard <- colData(sce)$discard
  colData(sce)$cluster_discard[problematic_cells] <- TRUE
} else {
  cat("No clusters found with discard rate >",
      cluster_discard_thresh * 100,
      "%\n")
}
```

```{r, fig.width=6.5, fig.height=6}
plotUMAP(sce, color_by = "cluster_discard") +
  labs(title = "All cells to discard")
```

```{r summarize_metrics}
metrics <- list(
  sample_id = sample_id,
  total_cells = ncol(sce),
  nUMI_thresh = nUMI_thresh,
  nGenes_thresh = nGenes_thresh,
  mito_thresh = mito_thresh,
  contam_threshold = contam_threshold,
  qc_cells = sum(!colData(sce)[["cluster_discard"]]),
  discard_cells = sum(colData(sce)[["cluster_discard"]]),
  damaged_cells = sum(colData(sce)[["damaged"]]),
  contaminated_cells = sum(colData(sce)[["contaminated"]])
)
metrics[["discard_ratio"]] <- round(metrics$discard_cells / metrics$total_cells, 3)
print(metrics)
```

Sample `r metrics$sample_id` has `r metrics$qc_cells` cells which passed QC and `r metrics$discard_cells` cells marked for removal (`r metrics$discard_ratio * 100` %).

# Write outputs

```{r writing_outputs}
saveRDS(sce, path_sce_output)

sce_cleaned <- sce[, !colData(sce)$discard]
saveRDS(sce_cleaned, path_sce_output_cleaned)

writeLines(jsonlite::toJSON(metrics, pretty=TRUE), paste0(sample_id, "_cell_QC_metrics.json"))
```

# Session info

```{r sessionInfo}
print(sessionInfo())
```

```{r gc}
gc()
```
